# Site settings
title: "Xinyi (Cynthia) Fan"
email: xfan31@illinois.edu
description: >- # this means to ignore newlines until "baseurl:"
  Personal academic website of Xinyi (Cynthia) Fan, Computer Science Ph.D.
  student at the University of Illinois Urbana-Champaign.
url: "https://xinyifan11.github.io"
github_username: xinyifan11
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
timezone: America/New_York

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

author:
  name     : "Xinyi (Cynthia) Fan"
  avatar   : "/assets/images/profile.jpg"
  bio      : "Computer Science Ph.D. Student"
  location : "Urbana, Illinois"
  employer : "University of Illinois Urbana-Champaign"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:xfan31@illinois.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/YOUR-LINKEDIN-HANDLE/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/xinyifan11"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/YOUR-LINKEDIN-HANDLE/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/xinyifan11"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
